### ISSUE TITLE
実行速度がすごく遅い

### ISSUE THREAD

**Issue by komagata** [komagata/holiday_jp#17]
日付データYAML化の影響。

ref: http://docs.komagata.org/5230#comment-286492

**Comment by ichylinux** [comment]
HolidayJp#between()
HolidayJp#holiday?()

で、Holidaysクラスのインスタンスを毎回生成しているために、YAMLファイルを毎回ロードし、結果適に時間がかかっているようです。
私の環境ではメソッド呼び出しで毎回３秒程度要します。

一度ロードした祝日データをオンメモリに維持するために Holidaysクラスをシングルトン化するのはどうでしょうか？
手元の環境での検証では以前のような処理速度に戻りました。

* holiday_jp/holidays.rb
```ruby
  require 'singleton'
  
  module HolidayJp
    class Holidays
      include Singleton
  ...
```

* holiday_jp.rb
```ruby
  module HolidayJp
    def self.between(start, last)
      Holidays.instance.holidays.find_all do |date, _holiday|
        start <= date && date <= last
      end.map(&:last)
    end
  
    def self.holiday?(date)
      Holidays.instance.holidays[date]
    end
  end
```

**Comment by komagata** [comment]
Resolved via #18
